services:
  # DATABASE MASTER REPLICA
  short-link-database:
    image: "postgres:17"
    container_name: "short-link-database"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    command:
      - "postgres"
      - "-c"
      - "config_file=/etc/postgresql.conf"
    ports:
      - "5434:5432"
    volumes:
      - ./infrastructure/databases/short_link_db/config/postgresql.conf:/etc/postgresql.conf:ro
      - ./infrastructure/databases/short_link_db/init:/docker-entrypoint-initdb.d:ro
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -p 5432"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 10s
    networks:
      - short-url-system-bridge

  #DATABASE SLAVE REPLICA
  original-link-database:
    image: "postgres:17"
    container_name: "original-link-database"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    command:
      - "postgres"
      - "-c"
      - "config_file=/etc/postgresql.conf"
    ports:
      - "5432:5432"
    volumes:
      - ./infrastructure/databases/long_link_db/config/postgresql.conf:/etc/postgresql.conf:ro
      - ./infrastructure/databases/long_link_db/init:/docker-entrypoint-initdb.d:ro
    depends_on:
      short-link-database:
        condition: service_healthy
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -p 5432"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 10s
    networks:
      - short-url-system-bridge

  # CACHE
  redis-cache:
    image: "redis:8.2.3"
    container_name: "redis-cache"
    environment:
      - REDIS_USER=${REDIS_USER}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "$REDIS_PASSWORD", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - short-url-system-bridge

  # EXPORTERS
  short-link-database-exporter:
    image: prometheuscommunity/postgres-exporter:v0.18.1
    container_name: "short-link-database-exporter"
    depends_on:
      short-link-database:
        condition: service_healthy
    environment:
      - DATA_SOURCE_URI=short-link-database:5432/${POSTGRES_DB}?sslmode=disable
      - DATA_SOURCE_USER=${POSTGRES_USER}
      - DATA_SOURCE_PASS=${POSTGRES_PASSWORD}
    ports:
      - "9188:9187"
    networks:
      - short-url-system-bridge

  original-link-database-exporter:
    image: prometheuscommunity/postgres-exporter:v0.18.1
    container_name: "original-link-database-exporter"
    depends_on:
      original-link-database:
        condition: service_healthy
    environment:
      - DATA_SOURCE_URI=original-link-database:5432/${POSTGRES_DB}?sslmode=disable
      - DATA_SOURCE_USER=${POSTGRES_USER}
      - DATA_SOURCE_PASS=${POSTGRES_PASSWORD}
    ports:
      - "9189:9187"
    networks:
      - short-url-system-bridge

  redis-exporter:
    image: oliver006/redis_exporter:v1.80.1
    container_name: "redis-exporter"
    depends_on:
      redis-cache:
        condition: service_healthy
    environment:
      - REDIS_ADDR=redis://${REDIS_HOST}:${REDIS_PORT}
    ports:
      - "9121:9121"
    networks:
      - short-url-system-bridge

  # Хранение метрик
  prometheus:
    image: prom/prometheus:v3.9.1
    container_name: "prometheus"
    ports:
      - "9090:9090"
    volumes:
      - ./infrastructure/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:9090/-/healthy"]
      interval: 10s
      timeout: 5s
      retries: 30
    networks:
      - short-url-system-bridge

  # Хранение логов
  loki:
    image: grafana/loki:main-3acb310
    container_name: "loki"
    ports:
      - "3100:3100"
    volumes:
      - ./infrastructure/loki/config/config.yml:/etc/loki/config.yml:ro
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3100/ready"]
      interval: 10s
      timeout: 5s
      retries: 30
    networks:
      - short-url-system-bridge

  # Хранение трейсов
  tempo:
    image: grafana/tempo:2.4.1
    container_name: "tempo"
    command: ["-config.file=/etc/tempo/tempo.yaml"]
    ports:
      - "3200:3200"
    volumes:
      - ./infrastructure/tempo/config/tempo.yaml:/etc/tempo/tempo.yaml:ro
      - tempo_data:/var/tempo
    healthcheck:
      test: ["CMD-SHELL", "curl -f localhost:3200/api/health && echo 'ready'"]
      interval: 10s
      timeout: 5s
      retries: 30
    networks:
      - short-url-system-bridge

  # Агент для сбора- и передачи метрик, логов и трейсов
  alloy:
    image: grafana/alloy:v1.12.2
    container_name: "alloy"
    user: root
    ports:
      - "9080:9080" # HTTP
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP
    volumes:
      - ./infrastructure/alloy/config.alloy:/etc/alloy/config.alloy:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/log:/var/log:ro
    environment:
      GRAFANA_LOKI_URL: http://loki:3100/loki/api/v1/push
    command:
      - run
      - --server.http.listen-addr=0.0.0.0:9080
      - --storage.path=/var/lib/alloy/data
      - /etc/alloy/config.alloy
    networks:
      - short-url-system-bridge

    #UI для телеметрии
  grafana:
    image: grafana/grafana:12.4.0-20836657505
    container_name: "grafana"
    ports:
      - "3000:3000"
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}
      GF_METRICS_ENABLED: true
    volumes:
      - ./infrastructure/grafana/provisioning:/etc/grafana/provisioning
      - ./infrastructure/grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      prometheus:
        condition: service_healthy
      loki:
        condition: service_started
      tempo:
        condition: service_started
      alloy:
        condition: service_started
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 60
    networks:
      - short-url-system-bridge

  original-links-getting-service:
    build:
      context: ./original-links-getting-service
      dockerfile: Dockerfile
    container_name: "original-links-getting-service"
    ports:
      - "8086:8086"
    working_dir: /app
    environment:
      SPRING_PROFILES_ACTIVE: dev
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USERNAME: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: original-link-database
      POSTGRES_PORT: 5432
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      OTLP_EXPORTER_ENDPOINT: http://tempo:4318
    depends_on:
      original-link-database:
        condition: service_healthy
      redis-cache:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:8086/actuator/health"]
      interval: 5s
      timeout: 5s
      retries: 30
    networks:
      - short-url-system-bridge

  short-link-creation-service:
    build:
      context: ./short-link-creation-service
      dockerfile: Dockerfile
    container_name: "short-link-creation-service"
    working_dir: /app
    ports:
      - "8087:8087"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USERNAME: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: short-link-database
      POSTGRES_PORT: 5432
      OTLP_EXPORTER_ENDPOINT: http://tempo:4318
    depends_on:
      short-link-database:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:8087/actuator/health"]
      interval: 5s
      timeout: 5s
      retries: 30
    networks:
      - short-url-system-bridge

  api:
    build:
      context: ./url-service-api
      dockerfile: Dockerfile
    container_name: "api"
    working_dir: /app
    ports:
      - "8085:8085"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      ORIGINAL_URL_SERVICE_BASE_URL: http://original-links-getting-service:8086
      SHORT_LINK_SERVICE_BASE_URL: http://short-link-creation-service:8087
      SHORT_LINK_ADDRESS_TEMPLATE: http://localhost:8085/
      OTLP_EXPORTER_ENDPOINT: http://tempo:4318
    depends_on:
      original-links-getting-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:8085/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 45
    networks:
      - short-url-system-bridge

networks:
  short-url-system-bridge: # Определение сети
    driver: bridge # Указываем тип - мост

volumes:
  tempo_data:
  loki_data:
  loki_chunks:
  loki_index:
  loki_rules:
