services:
  # MASTER REPLICA
  short-link-database:
    image: "postgres:17"
    container_name: "short-link-database"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: link_db
    command:
      - "postgres"
      - "-c"
      - "config_file=/etc/postgresql.conf"
    ports:
      - "5434:5432"
    volumes:
      - ./infrastructure/databases/short_link_db/config/postgresql.conf:/etc/postgresql.conf:ro
      - ./infrastructure/databases/short_link_db/init:/docker-entrypoint-initdb.d:ro
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -p 5432" ]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 10s

  # SLAVE REPLICA
  long-link-database:
    image: "postgres:17"
    container_name: "long-link-database"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: link_db
    command:
      - "postgres"
      - "-c"
      - "config_file=/etc/postgresql.conf"
    ports:
      - "5432:5432"
    volumes:
      - ./infrastructure/databases/long_link_db/config/postgresql.conf:/etc/postgresql.conf:ro
      - ./infrastructure/databases/long_link_db/init:/docker-entrypoint-initdb.d:ro
    depends_on:
      short-link-database:
        condition: service_healthy
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -p 5432"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 10s


