server:
  http_listen_port: 3200

distributor:
  receivers:
    otlp:
      protocols:
        grpc:    # default localhost:4317
        http:    # default localhost:4318

ingester:
  trace_idle_period: 10s # трейс пишется на диск если не было новых данных в течение 10 секунд

compactor:
  compaction:
    compacted_block_retention: 48h # хранить сжатые блоки 48 часов

storage:
  trace:
    backend: local # локальное хранилище для блоков трейсов
    local:
      path: /var/tempo/traces # путь для хранения блоков трейсов

