global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: [ "prometheus:9090" ]

  - job_name: "api"
    metrics_path: "actuator/prometheus"
    static_configs:
      - targets: [ "api:8085" ]

  - job_name: "original-links-getting-service"
    metrics_path: "actuator/prometheus"
    static_configs:
      - targets: [ "original-links-getting-service:8086" ]

  - job_name: "short-link-creation-service"
    metrics_path: "actuator/prometheus"
    static_configs:
      - targets: [ "short-link-creation-service:8087" ]

  - job_name: "short-link-database"
    static_configs:
      - targets: [ "short-link-database-exporter:9187" ]

  - job_name: "original-link-database"
    static_configs:
      - targets: [ "original-link-database-exporter:9187" ]

  - job_name: "redis-cache"
    static_configs:
      - targets: [ "redis-exporter:9121" ]

  - job_name: "grafana"
    metrics_path: "/metrics"
    static_configs:
      - targets: [ "grafana:3000" ]

  - job_name: "alloy"
    metrics_path: "/metrics"
    static_configs:
      - targets: [ "alloy:9080" ]

  - job_name: "loki"
    metrics_path: "/metrics"
    static_configs:
      - targets: [ "loki:3100" ]

  - job_name: "tempo"
    metrics_path: "/metrics"
    static_configs:
      - targets: [ "tempo:3200" ]
